FORWARD_ACCELERATION = 0.05;
FORWARD_MAX_SPEED = 3.5;

BACKWARD_ACCELERATION = -0.025;
BACKWARD_MAX_SPEED = -1;

IDLE_FRICTION = 0.03;
FORWARD_BRAKING_FRICTION = 0.08;

TURN_ANGULAR_VELOCITY = 2;

direction = 0;
speed = 0;
friction = 0;
